import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer";
import ClientLayout from "@/components/ClientLayout"; // Import your client-side component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "C-U International Language School",
  description: "Generated by create next app",
};

// RootLayout component that wraps the structure
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <ClientLayout>{children}</ClientLayout>
        <Footer />
      </body>
    </html>
  );
}
